version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - qodo_network

  webhook-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - GITLAB_API_TOKEN=${GITLAB_API_TOKEN}
      - GITLAB_API_URL=${GITLAB_API_URL}
      - GITLAB_USERNAME=${GITLAB_USERNAME}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - API_KEY=${API_KEY}
      - APP_URL=${APP_URL}
      - QODO_EMBED_API_KEY=${QODO_EMBED_API_KEY}
      - QODO_EMBED_API_URL=${QODO_EMBED_API_URL}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_API_URL=${OPENROUTER_API_URL}
      - TEMP_DIR=/app/temp
      - SEQUENTIAL_THINKING_THOUGHTS_COUNT=${SEQUENTIAL_THINKING_THOUGHTS_COUNT}
      # QDrant Configuration
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_CODE_COLLECTION=${QDRANT_CODE_COLLECTION}
      - QDRANT_DOCS_COLLECTION=${QDRANT_DOCS_COLLECTION}
      - USE_QDRANT=${USE_QDRANT}
      - QDRANT_FALLBACK_TO_DB=${QDRANT_FALLBACK_TO_DB}
    volumes:
      - ./temp:/app/temp
    depends_on:
      - qdrant
    restart: unless-stopped
    networks:
      - qodo_network

volumes:
  qdrant_storage:
    driver: local

networks: 
  qodo_network:
    external: true
